oro_entity_config:
    extend:
        field:
            items:
                #
                # Boolean parameter. If true - field data will be saved in serialized_data column without
                #  doctrine schema update
                #
                is_serialized:
                    options:
                        indexed:            true
                    grid:
                        type:               boolean
                        label:              DataBase field
                        filter_type:        boolean
                        required:           true
                        sortable:           true
                        filterable:         true
                        show_filter:        false
    datagrid:
        field:
            items:
                show_filter:
                    options:
                        required_properties:
                            -
                               config_id:
                                  scope:  extend
                               code:      is_serialized
                               value:     false
