parameters:
    oro_serialized_fields.migration.searilized_data.post_up.listener.class: Oro\Bundle\EntitySerializedFieldsBundle\EventListener\SerializedDataPostUpMigrationListener
    oro_serialized_fields.serialized_generator.extension.class:   Oro\Bundle\EntitySerializedFieldsBundle\Tools\GeneratorExtensions\SerializedDataGeneratorExtension

    oro_serialized_fields.datagrid.column_options_guesser.class:  Oro\Bundle\EntitySerializedFieldsBundle\Grid\SerializedColumnOptionsGuesser
    oro_serialized_fields.datagrid.serialized_fields_extension.class: Oro\Bundle\EntitySerializedFieldsBundle\Grid\SerializedFieldsExtension
    oro_serialized_fields.exclusion_provider.serialized_field.class: Oro\Bundle\EntitySerializedFieldsBundle\Provider\ConfigSerializedFieldExclusionProvider


    oro_serialized_fields.form.extension.field_extension.class: Oro\Bundle\EntitySerializedFieldsBundle\Form\Extension\FieldTypeExtension
    oro_serialized_fields.form.type.is_serialized_field.class: Oro\Bundle\EntitySerializedFieldsBundle\Form\Type\IsSerializedFieldType

    oro_serialized_fields.listener.extend_field.class: Oro\Bundle\EntitySerializedFieldsBundle\EventListener\ExtendFieldListener

services:
    oro_serialized_fields.migration.searilized_data.post_up.listener:
          class: %oro_serialized_fields.migration.searilized_data.post_up.listener.class%
          arguments:
              - @oro_entity_extend.migration.entity_metadata_helper
          tags:
              - { name: kernel.event_listener, event: oro_migration.post_up, method: onPostUp, priority: -100 }

    oro_serialized_fields.serialized_generator.extension:
        class: %oro_serialized_fields.serialized_generator.extension.class%
        arguments:
            - @oro_entity_config.provider.extend
        tags:
            - { name: oro_entity_extend.entity_generator_extension }

    oro_serialized_fields.datagrid.column_options_guesser:
        class: %oro_serialized_fields.datagrid.column_options_guesser.class%
        arguments:
            - @oro_entity_config.config_manager
        tags:
            - { name: oro_datagrid.column_options_guesser }

    oro_serialized_fields.datagrid.serialized_fields_extension:
        class: %oro_serialized_fields.datagrid.serialized_fields_extension.class%
        arguments:
            - @oro_entity_config.config_manager
            - @oro_entity.orm.entity_class_resolver
            - @oro_datagrid.datagrid.guesser
        tags:
            - { name: oro_datagrid.extension }

    oro_serialized_fields.form.extension.field_extension:
        class: %oro_serialized_fields.form.extension.field_extension.class%
        arguments:
            - @session
            - @form.factory
        tags:
            - { name: form.type_extension, alias: oro_entity_extend_field_type }

    oro_serialized_fields.form.type.is_serialized_field:
        class: %oro_serialized_fields.form.type.is_serialized_field.class%
        tags:
            - { name: form.type, alias: oro_serialized_fields_is_serialized_type }

    oro_serialized_fields.listener.extend_field:
        class: %oro_serialized_fields.listener.extend_field.class%
        arguments:
            - @oro_entity_extend.tools.dumper
            - @session
        tags:
            - { name: kernel.event_listener, event: oro_entity_extend.before_persist_field, method: beforePersist }
            - { name: kernel.event_listener, event: oro_entity_extend.after_flush_field, method: afterFlush }
            - { name: kernel.event_listener, event: oro_entity_extend.collect_field_options, method: collectOptions }

    oro_serialized_fields.exclusion_provider.serialized_field:
        class: %oro_serialized_fields.exclusion_provider.serialized_field.class%
        arguments:
            - @oro_entity_config.provider.extend

    oro_query_designer.exclusion_provider:
        class: %oro_entity.exclusion_provider.chain.class%
        calls:
            - [addProvider, [@oro_entity.exclusion_provider]]
            - [addProvider, [@oro_entity.exclusion_provider.dictionary]]
            - [addProvider, [@oro_serialized_fields.exclusion_provider.serialized_field]]
