parameters:
    oro_serialized_fields.migration.searilized_data.post_up.listener.class: Oro\Bundle\EntitySerializedFieldsBundle\EventListener\SerializedDataPostUpMigrationListener
    oro_serialized_fields.serialized_generator.extension.class:   Oro\Bundle\EntitySerializedFieldsBundle\Tools\GeneratorExtensions\SerializedDataGeneratorExtension

services:

    oro_serialized_fields.migration.searilized_data.post_up.listener:
          class: %oro_serialized_fields.migration.searilized_data.post_up.listener.class%
          arguments:
              - @oro_entity_extend.migration.entity_metadata_helper
          tags:
              - { name: kernel.event_listener, event: oro_migration.post_up, method: onPostUp, priority: -100 }

    oro_serialized_fields.serialized_generator.extension:
        class: %oro_serialized_fields.serialized_generator.extension.class%
        arguments:
            - @oro_entity_config.provider.extend
        tags:
            - { name: oro_entity_extend.entity_generator_extension }